fix: update unit-build.yml (#1294)
Your unit-test coverage report stops uploading about 2 month ago (just like with Fedot.Industrial). It is almost invisible issue, because it doesn't invoke any exception during execution. But it could be found in action logs if you unfold `Codecove-coverage`:

Error: Codecov token not found. Please provide Codecov token with -t flag.
Warning: Codecov: Failed to properly create commit: The process '/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov' failed with exit code 1